name: Deploy Timesheet App to On-Prem Ubuntu 22 Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to main

jobs:
  deploy:
    name: Deploy to On-Prem Ubuntu Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from GitHub
        uses: actions/checkout@v3

      - name: Setup SSH Access to Ubuntu 22 Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy Code to On-Prem Server
        run: |
          rsync -avz --delete ./ \
            chileson-2025@${{ secrets.SERVER_IP }}:/home/chileson-2025/timesheet_deploy_updated

      - name: Verify Latest Commit on Server
        run: |
          ssh chileson-2025@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/chileson-2025/timesheet_deploy_updated
            echo "Latest commit deployed:"
            git log -1 --oneline || echo "Git metadata not available"
          EOF

      - name: Restart Docker with Rebuild
        run: |
          ssh chileson-2025@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/chileson-2025/timesheet_deploy_updated
            echo "Stopping existing containers..."
            docker-compose down --remove-orphans
            echo "Starting updated containers with rebuild..."
            docker-compose up --build -d
          EOF
